# Analytics Calculation Notebook

### Mount Google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

### Load in Ground Truth Data

In [ ]:
# Load in ground truth data
all_test_set_path = '/content/drive/Shareddrives/LLMs_Art_Project/Data/Embeddings/Ground_Truth_Embeddings/all_test_set.csv'
all_test_set_df = pd.read_csv(all_test_set_path)

In [ ]:
all_test_set_df.head()

,art_style,painting,emotion,utterance,repetition,embeddings
0,Abstract_Expressionism,aaron-siskind_chicago-1951,sadness,dark and gloomy,6,"[0.022602325305342674, 0.012659378349781036, 0..."
1,Abstract_Expressionism,aaron-siskind_chicago-1951,fear,looks like some sort of creature from a scary ...,6,"[0.023607272654771805, 0.009993321262300014, -..."
2,Abstract_Expressionism,aaron-siskind_chicago-1951,fear,ghostly figure,6,"[-0.02539161965250969, -0.03483005613088608, 0..."
3,Abstract_Expressionism,aaron-siskind_chicago-1951,something else,This reminds me of more edgy modern art. Kinda...,6,"[0.030760714784264565, -0.009310646913945675, ..."
4,Abstract_Expressionism,aaron-siskind_chicago-1951,contentment,The light grey looks like the exhaust of two r...,6,"[0.013573752716183662, 0.027834365144371986, -..."

### Load in Results Data

In [ ]:
# Load in results
results_path = '/content/drive/Shareddrives/LLMs_Art_Project/Data/Results/Results_With_Embeddings/llama_results_0shot_embedded.csv'
results_df = pd.read_csv(results_path)

In [ ]:
results_df.head()

,test_painting,demo_paintings,demo_utterances,predicted_emotion,generated_description,embeddings
0,hans-hofmann_nulli-secundus-1964,"['mark-tobey_untitled-2', 'gene-davis_autumn-1...",['The orange colour curve look like orange pee...,amusement,the red color is very striking and the abstrac...,"[-0.0056884377263486385, -0.020650217309594154..."
1,gene-davis_color-needles-1984,"['jean-paul-riopelle_lithograph-1968', 'elaine...",['This feels like it started off great but som...,amusement,The colorful and dynamic arrangement of the ve...,"[0.002751436084508896, 0.013987968675792217, 0..."
2,arshile-gorky_bound-in-sleep,"['joan-snyder_still-2011', 'dan-flavin_juan-gr...",['The colors compliment each other very well a...,awe,The overall effect of the painting is one of c...,"[-0.03939918056130409, -0.004653977695852518, ..."
3,pino-pinelli_pittura-b-g-1991,"['esteban-vicente_comstock-1962', 'mark-tobey_...","['THIS LOOKS PRETTY BAD TO ME', 'An overly pop...",Awe,It is a beautiful piece of art.,"[-0.009846155531704426, -0.005903374403715134,..."
4,pyotr-konchalovsky_still-life-1911,"['esteban-vicente_harriet-1984', 'howard-mehri...",['The bright colors and almost disorganization...,something else,"The colors are fun and balanced well, but the ...","[0.009020834229886532, -0.005264392588287592, ..."

### Calculating Cosine Similarity, Append To Results Dataframe

In [ ]:
import numpy as np
import pandas as pd
import ast
from sklearn.metrics.pairwise import cosine_similarity

####doing this for human-human agreement

In [ ]:
# ---------------------------------------------------------
# 1. Helper: convert "embeddings" cell -> np.array
#    Handles: list, string "[...]", already-ndarray, NaN
# ---------------------------------------------------------
def to_embedding_array(x):
    # Already a numpy array
    if isinstance(x, np.ndarray):
        return x

    # Already a Python list of numbers
    if isinstance(x, list):
        return np.array(x, dtype=float)

    # String representation: "[0.1, 0.2, ...]"
    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)
            return np.array(parsed, dtype=float)
        except Exception as e:
            raise ValueError(f"Could not parse embedding string: {x[:80]}...") from e

    # Missing value
    if pd.isna(x):
        return np.array([], dtype=float)

    # Anything else is unexpected
    raise TypeError(f"Unexpected embedding type: {type(x)} with value {x}")

In [ ]:
# ---------------------------------------------------------
# 2. Apply conversion to BOTH dataframes
# ---------------------------------------------------------
all_test_set_df["embedding_vec"] = all_test_set_df["embeddings"].apply(to_embedding_array)

# (Optional but nice) Drop any GT rows with empty embeddings
#all_test_set_df = all_test_set_df[
#    all_test_set_df["embedding_vec"].apply(lambda a: isinstance(a, np.ndarray) and a.size > 0)
#]

# ---------------------------------------------------------
# 3. Group ground-truth rows by painting ID
# ---------------------------------------------------------
gt_groups = {pid: group for pid, group in all_test_set_df.groupby("painting")}

# ---------------------------------------------------------
# 4. Function to compute:
#    - max cosine similarity
#    - index of best-matching GT row (global index)
#    - the GT description text (change column name as needed)
# ---------------------------------------------------------
def get_best_human_match(row):
    painting = row["painting"]
    v = row["embedding_vec"]
    current_index = row.name  # <-- index to exclude

    if not isinstance(v, np.ndarray) or v.size == 0:
        return pd.Series({
            "max_cosine_similarity": np.nan,
            "best_other_index": None,
            "best_other_description": None
        })

    query_emb = v.reshape(1, -1)

    # no GT group?
    if painting not in gt_groups:
        return pd.Series({
            "max_cosine_similarity": np.nan,
            "best_other_index": None,
            "best_other_description": None
        })

    # get all other GT rows for this painting
    gt_df = gt_groups[painting]

    # remove empty embeddings
    gt_df = gt_df[gt_df["embedding_vec"].apply(lambda a: isinstance(a, np.ndarray) and a.size > 0)]

    # exclude itself
    gt_df = gt_df[gt_df.index != current_index]

    if gt_df.empty:
        return pd.Series({
            "max_cosine_similarity": np.nan,
            "best_other_index": None,
            "best_other_description": None
        })

    # stack embeddings
    gt_embs = np.stack(gt_df["embedding_vec"].values)

    # cosine similarity
    sim_scores = cosine_similarity(query_emb, gt_embs)[0]

    best_idx_local = int(sim_scores.argmax())
    best_sim = float(sim_scores[best_idx_local])
    best_row = gt_df.iloc[best_idx_local]

    return pd.Series({
        "max_cosine_similarity": best_sim,
        "best_other_index": best_row.name,
        "best_other_description": best_row["utterance"]  # change as needed
    })

# ---------------------------------------------------------
# 5. Apply to every model-generated result
# ---------------------------------------------------------
all_test_set_df[[
    "human_max_cosine_similarity",
    "human_best_other_index",
    "human_best_other_description"
]] = all_test_set_df.apply(get_best_human_match, axis=1)

####doing this for ai-human agreement

In [ ]:
# ---------------------------------------------------------
# 1. Helper: convert "embeddings" cell -> np.array
#    Handles: list, string "[...]", already-ndarray, NaN
# ---------------------------------------------------------
def to_embedding_array(x):
    # Already a numpy array
    if isinstance(x, np.ndarray):
        return x

    # Already a Python list of numbers
    if isinstance(x, list):
        return np.array(x, dtype=float)

    # String representation: "[0.1, 0.2, ...]"
    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)
            return np.array(parsed, dtype=float)
        except Exception as e:
            raise ValueError(f"Could not parse embedding string: {x[:80]}...") from e

    # Missing value
    if pd.isna(x):
        return np.array([], dtype=float)

    # Anything else is unexpected
    raise TypeError(f"Unexpected embedding type: {type(x)} with value {x}")

In [ ]:
# ---------------------------------------------------------
# 2. Apply conversion to BOTH dataframes
# ---------------------------------------------------------
results_df["embedding_vec"] = results_df["embeddings"].apply(to_embedding_array)
all_test_set_df["embedding_vec"] = all_test_set_df["embeddings"].apply(to_embedding_array)

# (Optional but nice) Drop any GT rows with empty embeddings
#all_test_set_df = all_test_set_df[
#    all_test_set_df["embedding_vec"].apply(lambda a: isinstance(a, np.ndarray) and a.size > 0)
#]

# ---------------------------------------------------------
# 3. Group ground-truth rows by painting ID
# ---------------------------------------------------------
gt_groups = {pid: group for pid, group in all_test_set_df.groupby("painting")}

# ---------------------------------------------------------
# 4. Function to compute:
#    - max cosine similarity
#    - index of best-matching GT row (global index)
#    - the GT description text (change column name as needed)
# ---------------------------------------------------------
def get_best_gt_match(row):
    painting = row["test_painting"]
    v = row["embedding_vec"]

    # If this embedding is empty or invalid, skip
    if not isinstance(v, np.ndarray) or v.size == 0:
        return pd.Series({
            "max_cosine_sim": np.nan,
            "best_gt_index": None,
            "best_gt_description": None
        })

    gen_emb = v.reshape(1, -1)

    # If no ground truth exists for this painting
    if painting not in gt_groups:
        return pd.Series({
            "max_cosine_sim": np.nan,
            "best_gt_index": None,
            "best_gt_description": None
        })

    # Ground truth dataframe for this painting
    gt_df = gt_groups[painting]

    # Safety: filter out any empty embeddings in GT
    gt_df = gt_df[gt_df["embedding_vec"].apply(lambda a: isinstance(a, np.ndarray) and a.size > 0)]
    if gt_df.empty:
        return pd.Series({
            "max_cosine_sim": np.nan,
            "best_gt_index": None,
            "best_gt_description": None
        })

    gt_embs = np.stack(gt_df["embedding_vec"].values)  # shape (k, d)

    # Compute cosine similarity scores
    sim_scores = cosine_similarity(gen_emb, gt_embs)[0]  # shape (k,)

    # Get the best (highest) score
    best_idx_local = int(sim_scores.argmax())      # index within this group
    best_sim = float(sim_scores[best_idx_local])   # best similarity score
    best_gt_row = gt_df.iloc[best_idx_local]       # full GT row
    best_global_index = best_gt_row.name           # index in all_test_set_df

    return pd.Series({
        "max_cosine_similarity": best_sim,
        "best_gt_index": best_global_index,
        # CHANGE THIS to your actual GT text column name:
        "best_gt_description": best_gt_row["utterance"]
    })

# ---------------------------------------------------------
# 5. Apply to every model-generated result
# ---------------------------------------------------------
results_df[["max_cosine_similarity", "best_gt_index", "best_gt_description"]] = results_df.apply(get_best_gt_match, axis=1)

In [ ]:
results_df.head()

,test_painting,demo_paintings,demo_utterances,predicted_emotion,generated_description,embeddings,embedding_vec,max_cosine_similarity,best_gt_index,best_gt_description
0,hans-hofmann_nulli-secundus-1964,[],[],Something-Else,I feel like this painting is very abstract and...,"[-0.0195406936109066, -0.05804502218961716, 0....","[-0.0195406936109066, -0.05804502218961716, 0....",0.698429,101,The painting makes me feel like I am walking d...
1,gene-davis_color-needles-1984,[],[],Awe,The use of thin lines in a horizontal pattern ...,"[0.016316348686814308, 0.014112216420471668, 0...","[0.016316348686814308, 0.014112216420471668, 0...",0.663300,423,The center of the painting seems to be bright....
2,arshile-gorky_bound-in-sleep,[],[],Awe,The use of bright colors and the way the face ...,"[-0.014129390008747578, -0.02588188275694847, ...","[-0.014129390008747578, -0.02588188275694847, ...",0.758641,541,"the calm demeanor of the face, the chalk like ..."
3,pino-pinelli_pittura-b-g-1991,[],[],amusement,it looks like a donut with the white cream and...,"[-0.0293964222073555, 0.035130731761455536, -0...","[-0.0293964222073555, 0.035130731761455536, -0...",0.626463,766,The fruity donuts glued onto the wall is funny...
4,pyotr-konchalovsky_still-life-1911,[],[],Contentment,The shapes are simple and make me feel calm,"[-0.0008190866210497916, 0.009310310706496239,...","[-0.0008190866210497916, 0.009310310706496239,...",0.665668,694,i dont feel anything when I look at this

In [ ]:
gt_groups

{'aaron-siskind_chicago-1951':                 art_style                    painting         emotion  \
 0  Abstract_Expressionism  aaron-siskind_chicago-1951         sadness
 1  Abstract_Expressionism  aaron-siskind_chicago-1951            fear
 2  Abstract_Expressionism  aaron-siskind_chicago-1951            fear
 3  Abstract_Expressionism  aaron-siskind_chicago-1951  something else
 4  Abstract_Expressionism  aaron-siskind_chicago-1951     contentment
 5  Abstract_Expressionism  aaron-siskind_chicago-1951             awe

                                            utterance  repetition  \
 0                                    dark and gloomy           6
 1  looks like some sort of creature from a scary ...           6
 2                                     ghostly figure           6
 3  This reminds me of more edgy modern art. Kinda...           6
 4  The light grey looks like the exhaust of two r...           6
 5        The textures are very appealing to look at.           6

                                           embeddings  \
 0  [0.022602325305342674, 0.012659378349781036, 0...
 1  [0.023607272654771805, 0.009993321262300014, -...
 2  [-0.02539161965250969, -0.03483005613088608, 0...
 3  [0.030760714784264565, -0.009310646913945675, ...
 4  [0.013573752716183662, 0.027834365144371986, -...
 5  [-0.011116745881736279, 0.004843595903366804, ...

                                        embedding_vec
 0  [0.022602325305342674, 0.012659378349781036, 0...
 1  [0.023607272654771805, 0.009993321262300014, -...
 2  [-0.02539161965250969, -0.03483005613088608, 0...
 3  [0.030760714784264565, -0.009310646913945675, ...
 4  [0.013573752716183662, 0.027834365144371986, -...
 5  [-0.011116745881736279, 0.004843595903366804, ...  ,
 'aki-kuroda_untitled-1998':                  art_style                  painting         emotion  \
 6   Abstract_Expressionism  aki-kuroda_untitled-1998      excitement
 7   Abstract_Expressionism  aki-kuroda_untitled-1998  something else
 8   Abstract_Expressionism  aki-kuroda_untitled-1998             awe
 9   Abstract_Expressionism  aki-kuroda_untitled-1998     contentment
 10  Abstract_Expressionism  aki-kuroda_untitled-1998     contentment

                                             utterance  repetition  \
 6   the colors are so vibrant and there's no real ...           5
 7   it makes me feel loving. it looks like two com...           5
 8   The white space in the painting resembles a sl...           5
 9   The combination of the blue and black is very ...           5
 10  Darks blue and black, like darkly dyed cloth, ...           5

                                            embeddings  \
 6   [0.02224212884902954, -0.030366240069270134, 0...
 7   [-0.032402731478214264, -0.0140151996165514, 0...
 8   [-0.04229440540075302, -0.021981656551361084, ...
 9   [-0.010826422832906246, -0.004135718569159508,...
 10  [0.034981343895196915, -0.03402210399508476, -...

                                         embedding_vec
 6   [0.02224212884902954, -0.030366240069270134, 0...
 7   [-0.032402731478214264, -0.0140151996165514, 0...
 8   [-0.04229440540075302, -0.021981656551361084, ...
 9   [-0.010826422832906246, -0.004135718569159508,...
 10  [0.034981343895196915, -0.03402210399508476, -...  ,
 'albert-gleizes_untitled-2':     art_style                   painting         emotion  \
 532    Cubism  albert-gleizes_untitled-2  something else
 533    Cubism  albert-gleizes_untitled-2       amusement
 534    Cubism  albert-gleizes_untitled-2         sadness
 535    Cubism  albert-gleizes_untitled-2     contentment
 536    Cubism  albert-gleizes_untitled-2  something else

                                              utterance  repetition  \
 532  I kind of feel indifferent to it, whats on the...           5
 533  The segue from moonlit scene to still life of ...           5
 534  The dark colors and blurry lines makes me feel...           5
 535  a welcoming tray of sustenance to enjoy by my ...           5
 536  Thoughtful as this is abstract and I must stan...           5

                                             embeddings  \
 532  [0.00411009369418025, -0.00169076444581151, 0....
 533  [-0.07059283554553986, -0.031053267419338226, ...
 534  [0.016740338876843452, 0.026998570188879967, 0...
 535  [-0.022869374603033066, 0.017794696614146233, ...
 536  [0.02208130620419979, -0.00024995976127684116,...

                                          embedding_vec
 532  [0.00411009369418025, -0.00169076444581151, 0....
 533  [-0.07059283554553986, -0.031053267419338226, ...
 534  [0.016740338876843452, 0.026998570188879967, 0...
 535  [-0.022869374603033066, 0.017794696614146233, ...
 536  [0.02208130620419979, -0.00024995976127684116,...  ,
 'alfred-jensen_interlacing-colors-i-1959':                 art_style                                 painting  \
 222  Color_Field_Painting  alfred-jensen_interlacing-colors-i-1959
 223  Color_Field_Painting  alfred-jensen_interlacing-colors-i-1959
 224  Color_Field_Painting  alfred-jensen_interlacing-colors-i-1959
 225  Color_Field_Painting  alfred-jensen_interlacing-colors-i-1959
 226  Color_Field_Painting  alfred-jensen_interlacing-colors-i-1959

             emotion                                          utterance  \
 222  something else  Irritated. Some modern art does this to me, an...
 223  something else  Confusion as there is just random shapes in th...
 224  something else      Itseemskindoflikeaposteryou'dputinaclassroom.
 225  something else  Confused because not sure what the picture is ...
 226     contentment  It reminds me of old board games because they ...

      repetition                                         embeddings  \
 222           5  [0.015426247380673885, 0.010904994793236256, 0...
 223           5  [0.009975939989089966, 0.00920950435101986, 0....
 224           5  [-0.0187072791159153, 0.009470464661717415, 0....
 225           5  [0.04544102028012276, 0.008943525142967701, -0...
 226           5  [-0.03517591580748558, -0.017587821930646896, ...

                                          embedding_vec
 222  [0.015426247380673885, 0.010904994793236256, 0...
 223  [0.009975939989089966, 0.00920950435101986, 0....
 224  [-0.0187072791159153, 0.009470464661717415, 0....
 225  [0.04544102028012276, 0.008943525142967701, -0...
 226  [-0.03517591580748558, -0.017587821930646896, ...  ,
 'alvaro-lapa_o-casamento-1967':       art_style                      painting         emotion  \
 706  Minimalism  alvaro-lapa_o-casamento-1967       amusement
 707  Minimalism  alvaro-lapa_o-casamento-1967            fear
 708  Minimalism  alvaro-lapa_o-casamento-1967       amusement
 709  Minimalism  alvaro-lapa_o-casamento-1967  something else
 710  Minimalism  alvaro-lapa_o-casamento-1967       amusement

                                              utterance  repetition  \
 706  The interesting shapes and minimal use of colo...           5
 707  The bold black brush strokes are disturbing to...           5
 708  i like if you look close you can see different...           5
 709  Confused - I do not understand what this image...           5
 710               This is very interesting to look at.           5

                                             embeddings  \
 706  [0.01945449225604534, 0.02192726731300354, -0....
 707  [0.003525424748659134, 0.00036171296960674226,...
 708  [-0.006273071747273207, 0.05443042144179344, 0...
 709  [0.02820388413965702, 0.007854473777115345, 0....
 710  [0.007507516071200371, 0.0050860135816037655, ...

                                          embedding_vec
 706  [0.01945449225604534, 0.02192726731300354, -0....
 707  [0.003525424748659134, 0.00036171296960674226,...
 708  [-0.006273071747273207, 0.05443042144179344, 0...
 709  [0.02820388413965702, 0.007854473777115345, 0....
 710  [0.007507516071200371, 0.0050860135816037655, ...  ,
 'andre-pierre-arnal_pliage-folded-painting-1975':                 art_style                                        painting  \
 227  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 228  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 229  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 230  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 231  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 232  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 233  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 234  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 235  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 236  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 237  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 238  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 239  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 240  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 241  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 242  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 243  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 244  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 245  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 246  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 247  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 248  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 249  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 250  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 251  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 252  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 253  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 254  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 255  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 256  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 257  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 258  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 259  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 260  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 261  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 262  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 263  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 264  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 265  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 266  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 267  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 268  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 269  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 270  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 271  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 272  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 273  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 274  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 275  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 276  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 277  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975
 278  Color_Field_Painting  andre-pierre-arnal_pliage-folded-painting-1975

             emotion                                          utterance  \
 227     contentment               It's calming. The colors are neutral
 228     contentment  The simple nature of the painting is satisfyin...
 229  something else  interested: the shapes make an interesting pat...
 230           anger                                    Unclear picture
 231             awe                  itlookslikeaveryoldpaintedtextile
 232     contentment  I can almost feel the tapestry. It feels soft ...
 233  something else                   Not sure what the picture means.
 234  something else  Frustration. Two tone, simple shapes. Some tri...
 235             awe  how painting is consisting of geometrical shap...
 236  something else                           The picture is very old.
 237      excitement  It brings to mind the excitement of finding a ...
 238     contentment  I like subtle tones of this painting, as it br...
 239         sadness  The triangles that are decorating this piece o...
 240       amusement  This painting reminds me of the school craft p...
 241             awe  The geometric pattern and warm colours looks g...
 242  something else  Iâ€™m not quite sure what to think of this pai...
 243  something else  This image makes me feel relaxed with the natu...
 244  something else  The weird brown shapes on a tan background is ...
 245     contentment  The earth tones of the piece have a natural fe...
 246             awe  The symbol appears to be of some unknown, myst...
 247      excitement  I am intrigued by the symmetry in these shapes...
 248     contentment  The print seems old, and is repeated along the...
 249  something else  Nothing, I feel nothing looking at this, it fe...
 250     contentment  The neutral design and coloring does not cause...
 251         sadness  The triangular patterns appear to be marred by...
 252  something else  A paint canvas of brown, beige with a hint of ...
 253  something else  This is very boring to me with only shades of ...
 254  something else  I'm not sure if this is a painting or material...
 255  something else  I feel interested because I do not know what I...
 256  something else  This is boring and doesn't look very nice, mor...
 257             awe  The patterns look like they're made with sponges.
 258             awe  The symmetry of the dark brown makes me feel h...
 259     contentment  This reminds me of the sewing cloth my sister ...
 260  something else  I'm confused by the painting because I have no...
 261      excitement   the triangular pattern is edging and stimulative
 262  something else  This is very dull to me as the uninspired abst...
 263  something else        The bland color makes the image monotonous.
 264       amusement  This semi-checkered pattern kind of reminds me...
 265     contentment  Looks like a quilt that use to be at my grandm...
 266     contentment  This pink and sepia pattern of triangles exude...
 267     contentment  Offwhites and light browns looks like tye dye....
 268  something else  This looks like it's just a quilt that you wou...
 269  something else  looks like a tribal print or decoration on a p...
 270     contentment  The design looks like it would make a beautifu...
 271     contentment  The pattern and shape looks like a comfortable...
 272  something else  Not really art to me. Kind of looks like a clo...
 273             awe  Reminds me of one of my grandfathers handkerch...
 274            fear  The old tapestry seems to have a skull shape o...
 275         sadness  The cream-like color palette used invokes nost...
 276  something else  these patches look like homemade napkins made ...
 277     contentment  The designs and material are faded giving the ...
 278     contentment  This sheet here is unique and looks great to s...

      repetition                                         embeddings  \
 227          52  [-0.013680587522685528, -0.03847958520054817, ...
 228          52  [-0.0250959824770689, -0.0064891306683421135, ...
 229          52  [0.048353392630815506, -0.04373345896601677, -...
 230          52  [0.0035406833048909903, 0.015518841333687305, ...
 231          52  [-0.04704095050692558, -0.0458298958837986, 0....
 232          52  [-0.0019705609884113073, -0.06855503469705582,...
 233          52  [0.008993773721158504, 0.0036299745552241802, ...
 234          52  [0.023814644664525986, 0.0014447247376665473, ...
 235          52  [-0.015697557479143143, 0.006250539794564247, ...
 236          52  [-0.023995431140065193, 0.007610140834003687, ...
 237          52  [-0.07940242439508438, -0.013458866626024246, ...
 238          52  [-0.005724005401134491, -0.00724291056394577, ...
 239          52  [0.03490842878818512, -0.03485862538218498, 0....
 240          52  [-0.003963160328567028, -0.04236790910363197, ...
 241          52  [0.036103229969739914, -0.015430156141519547, ...
 242          52  [-0.02566797100007534, -0.04343302175402641, -...
 243          52  [0.01859918422996998, -0.007013220805674791, 0...
 244          52  [0.030411912128329277, 0.03181751072406769, -0...
 245          52  [0.04163191840052605, -0.05342167615890503, 0....
 246          52  [-0.010907736606895924, 0.01581452414393425, -...
 247          52  [0.02112727425992489, 0.010030259378254414, 0....
 248          52  [0.00699961930513382, -0.00471310131251812, 0....
 249          52  [0.024763060733675957, -0.01663076877593994, 0...
 250          52  [-0.0011177397100254893, -0.012537403032183647...
 251          52  [-0.0007199380779638886, 0.014325753785669804,...
 252          52  [-0.043605782091617584, -0.03129562735557556, ...
 253          52  [0.022650843486189842, 0.004562446381896734, 0...
 254          52  [0.049585018306970596, -0.05123888701200485, -...
 255          52  [0.03504374623298645, -0.00339653086848557, -0...
 256          52  [0.04614679887890816, -0.0188799686729908, 0.0...
 257          52  [0.037184178829193115, -0.009916182607412338, ...
 258          52  [-0.011990697123110294, -0.0137445367872715, 0...
 259          52  [0.014929741621017456, -0.05452865734696388, -...
 260          52  [0.02405443973839283, -0.0025242664851248264, ...
 261          52  [-0.014792987145483494, -0.025003623217344284,...
 262          52  [0.061081480234861374, -0.04570133611559868, 0...
 263          52  [0.001937539898790419, -0.014307957142591476, ...
 264          52  [0.01090132724493742, -0.02722407504916191, -0...
 265          52  [-0.01711506024003029, -0.024575939401984215, ...
 266          52  [-0.04645342007279396, -0.039866842329502106, ...
 267          52  [0.007104143965989351, 0.008508737199008465, -...
 268          52  [0.019086478278040886, -0.026692615821957588, ...
 269          52  [0.03948145732283592, -0.0369279608130455, -0....
 270          52  [0.0029810850974172354, -0.011260942555963993,...
 271          52  [-0.0028539381455630064, -0.03819229453802109,...
 272          52  [0.027224309742450714, -0.028189055621623993, ...
 273          52  [-0.012453921139240265, -0.012483789585530758,...
 274          52  [-0.033254433423280716, -0.017360946163535118,...
 275          52  [-0.05754762142896652, -0.018925700336694717, ...
 276          52  [0.016337459906935692, -0.018423300236463547, ...
 277          52  [0.010210338979959488, -0.036247141659259796, ...
 278          52  [0.03208499401807785, -0.045470185577869415, 0...

                                          embedding_vec
 227  [-0.013680587522685528, -0.03847958520054817, ...
 228  [-0.0250959824770689, -0.0064891306683421135, ...
 229  [0.048353392630815506, -0.04373345896601677, -...
 230  [0.0035406833048909903, 0.015518841333687305, ...
 231  [-0.04704095050692558, -0.0458298958837986, 0....
 232  [-0.0019705609884113073, -0.06855503469705582,...
 233  [0.008993773721158504, 0.0036299745552241802, ...
 234  [0.023814644664525986, 0.0014447247376665473, ...
 235  [-0.015697557479143143, 0.006250539794564247, ...
 236  [-0.023995431140065193, 0.007610140834003687, ...

### Calculating Accuracy of Emotion Prediction and Append to Results Dataframe

####human-human

In [ ]:
# ---------------------------------------------------------
# Build painting → set of ALL human emotions
# (same as your original code)
# ---------------------------------------------------------
from collections import defaultdict

emotions_map = defaultdict(list)
for index, row in all_test_set_df.iterrows():
    painting = row['painting']
    emotion = str(row['emotion']).lower()
    emotions_map[painting].append(emotion)

In [ ]:
def compute_human_human_accuracy(row):
    painting = row["painting"]
    current_emotion = str(row["emotion"]).lower()

    all_emotions = [emo for emo in emotions_map[painting]]
    if current_emotion in all_emotions: all_emotions.remove(current_emotion)
    other_emotions = all_emotions

    # If no other annotators exist → undefined agreement
    if len(other_emotions) == 0:
        return np.nan

    # Does this human agree with at least one other human?
    return 1 if current_emotion in other_emotions else 0

In [ ]:
all_test_set_df["human_human_accuracy"] = all_test_set_df.apply(
    compute_human_human_accuracy,
    axis=1
)

In [ ]:
human_results_df = all_test_set_df.copy(deep=True)
human_results_df.rename(columns={'utterance': 'generated_description', 'emotion': 'predicted_emotion', 'painting': 'test_painting', 'human_max_cosine_similarity': 'max_cosine_similarity', 'human_human_accuracy': 'accuracy'}, inplace=True)

In [ ]:
human_results_df.head()

,art_style,test_painting,predicted_emotion,generated_description,repetition,embeddings,embedding_vec,max_cosine_similarity,human_best_other_index,human_best_other_description,accuracy
0,Abstract_Expressionism,aaron-siskind_chicago-1951,sadness,dark and gloomy,6,"[0.022602325305342674, 0.012659378349781036, 0...","[0.022602325305342674, 0.012659378349781036, 0...",0.658607,3,This reminds me of more edgy modern art. Kinda...,0
1,Abstract_Expressionism,aaron-siskind_chicago-1951,fear,looks like some sort of creature from a scary ...,6,"[0.023607272654771805, 0.009993321262300014, -...","[0.023607272654771805, 0.009993321262300014, -...",0.735977,2,ghostly figure,1
2,Abstract_Expressionism,aaron-siskind_chicago-1951,fear,ghostly figure,6,"[-0.02539161965250969, -0.03483005613088608, 0...","[-0.02539161965250969, -0.03483005613088608, 0...",0.735977,1,looks like some sort of creature from a scary ...,1
3,Abstract_Expressionism,aaron-siskind_chicago-1951,something else,This reminds me of more edgy modern art. Kinda...,6,"[0.030760714784264565, -0.009310646913945675, ...","[0.030760714784264565, -0.009310646913945675, ...",0.658607,0,dark and gloomy,0
4,Abstract_Expressionism,aaron-siskind_chicago-1951,contentment,The light grey looks like the exhaust of two r...,6,"[0.013573752716183662, 0.027834365144371986, -...","[0.013573752716183662, 0.027834365144371986, -...",0.534989,1,looks like some sort of creature from a scary ...,0

In [ ]:
overall_human_human_accuracy = human_results_df["accuracy"].mean()
print(f"Overall Human–Human Agreement: {overall_human_human_accuracy*100:.2f}%")

Overall Human–Human Agreement: 71.90%

####human-ai

In [ ]:
from collections import defaultdict

# Read in all__test set
#all_tests_df = pd.read_csv('/content/drive/Shareddrives/LLMs_Art_Project/Data/Embeddings/Ground_Truth_Embeddings/all_test_set.csv')


# Creating dictionary mapping paintings to utterances
emotions_map = defaultdict(set)
for index, row in all_test_set_df.iterrows():
    painting = row['painting']
    emotion = row['emotion'].lower()
    emotions_map[painting].add(emotion)

print(emotions_map)
print(len(emotions_map))

defaultdict(<class 'set'>, {'aaron-siskind_chicago-1951': {'something else', 'fear', 'sadness', 'contentment', 'awe'}, 'aki-kuroda_untitled-1998': {'excitement', 'something else', 'awe', 'contentment'}, 'atsuko-tanaka_untitled-1963': {'excitement', 'something else', 'disgust', 'amusement'}, 'brice-marden_etchings-to-rexroth-1-1986': {'something else', 'excitement', 'disgust', 'sadness', 'contentment', 'awe', 'anger'}, 'clyfford-still_ph-118-1947': {'excitement', 'something else', 'awe', 'amusement'}, 'esteban-vicente_balada-1959': {'fear', 'amusement'}, 'friedel-dzubas_echo-1958': {'something else', 'fear', 'anger'}, 'gerhard-richter_mediation': {'excitement', 'contentment', 'anger', 'amusement'}, 'hans-hofmann_bird-cage-variation-ii-1958': {'something else', 'fear', 'excitement', 'disgust', 'contentment', 'awe', 'amusement', 'anger'}, 'hans-hofmann_gloriamundi-1963': {'excitement', 'something else', 'sadness', 'amusement'}, 'hans-hofmann_little-cherry-1965': {'sadness', 'something else', 'awe', 'fear'}, 'hans-hofmann_nulli-secundus-1964': {'excitement', 'contentment', 'fear', 'anger'}, 'helen-frankenthaler_blue-form-in-a-scene-1961': {'something else', 'disgust', 'amusement'}, 'helen-frankenthaler_tuscany-1963': {'sadness', 'something else', 'fear', 'contentment'}, 'howard-mehring_all-green-1958': {'contentment', 'disgust', 'something else'}, 'jack-tworkov_indian-red-series-i-1979': {'excitement', 'sadness', 'contentment', 'amusement', 'anger'}, 'joan-snyder_perpetuo-eternally-2004': {'sadness', 'contentment', 'disgust', 'fear'}, 'kenzo-okada_untitled': {'something else', 'anger', 'awe', 'contentment'}, 'miriam-schapiro_fanfare-1968': {'excitement', 'something else', 'awe', 'contentment'}, 'philip-guston_to-b-w-t': {'something else', 'contentment', 'disgust', 'anger'}, 'ralph-hotere_song-cycle-1975': {'something else', 'fear', 'excitement', 'contentment', 'amusement', 'anger'}, 'richard-tuttle_20-pearls-1-2003': {'something else', 'fear', 'excitement', 'disgust', 'contentment', 'awe', 'amusement'}, 'salvador-dali_abraham-pater-multarem-gentium-genesis-12-1f-1967': {'something else', 'fear', 'excitement', 'contentment', 'awe'}, 'sam-gilliam_buoy-landscape-ii-1982': {'something else', 'excitement', 'disgust', 'contentment', 'awe', 'amusement'}, 'theodoros-stamos_untitled-columns-of-fire-1956': {'contentment', 'fear', 'something else', 'anger'}, 'william-baziotes_cyclops-1947': {'something else', 'fear', 'amusement'}, 'wu-guanzhong_white-poplar-woods': {'something else', 'contentment', 'awe', 'amusement'}, 'franz-kline_buttress-1956': {'sadness', 'disgust', 'fear', 'anger'}, 'jackson-pollock_black-white-number-20-1951': {'sadness', 'anger', 'fear', 'amusement'}, 'jackson-pollock_number-12-1949': {'something else', 'excitement', 'disgust', 'awe', 'anger'}, 'alfred-jensen_interlacing-colors-i-1959': {'something else', 'contentment'}, 'andre-pierre-arnal_pliage-folded-painting-1975': {'something else', 'fear', 'excitement', 'sadness', 'contentment', 'awe', 'amusement', 'anger'}, 'angelo-de-sousa_sem-titulo-1988': {'excitement', 'something else', 'anger', 'fear'}, 'anne-appleby_appleby-2011': {'something else', 'sadness', 'contentment', 'amusement', 'anger'}, 'anne-truitt_knight-s-heritage-1963': {'something else', 'fear', 'excitement', 'disgust', 'sadness', 'contentment', 'awe', 'amusement'}, 'barnett-newman_onement-v-1952': {'sadness', 'something else', 'anger'}, 'barnett-newman_tenth-station-1965': {'excitement', 'contentment', 'something else', 'amusement'}, 'barnett-newman_the-wild-1950': {'excitement', 'something else', 'contentment'}, 'charles-hinman_dance-1972': {'sadness', 'contentment', 'awe', 'amusement'}, 'dan-christensen_untitled-1968': {'something else', 'excitement', 'contentment', 'awe', 'amusement'}, 'friedel-dzubas_tundra-ii-1962': {'excitement', 'something else', 'disgust', 'amusement'}, 'gene-davis_cannonball-1969': {'sadness', 'something else', 'contentment'}, 'gene-davis_color-needles-1984': {'contentment', 'something else', 'amusement'}, 'gene-davis_diamond-jim-1972': {'something else', 'anger', 'contentment', 'amusement'}, 'gene-davis_untitled-pink-stripes-gray-box-1976': {'something else', 'fear', 'excitement', 'disgust', 'sadness', 'contentment', 'amusement', 'anger'}, 'helen-frankenthaler_distillation-1973': {'something else', 'anger', 'amusement'}, 'ian-davenport_puddle-painting-magenta-2008': {'sadness', 'anger', 'excitement', 'amusement'}, 'leon-berkowitz_dark-light-rose-gold-1978': {'excitement', 'something else', 'contentment', 'amusement'}, 'michel-carrade_unknown-title-14': {'something else', 'fear', 'excitement', 'contentment', 'awe'}, 'olivier-debre_rouge-coule-de-touraine-1990': {'excitement', 'something else', 'awe'}, 'paul-jenkins_phenomena-lands-end': {'sadness', 'contentment', 'awe', 'something else'}, 'ronnie-landfield_circe-s-palace-1982': {'excitement', 'contentment', 'disgust', 'fear'}, 'walter-darby-bannard_green-valentine-3-1965': {'excitement', 'something else', 'contentment', 'awe'}, 'william-scott_blue-form-on-white-1964': {'something else', 'contentment', 'disgust', 'amusement'}, 'albert-gleizes_untitled-2': {'sadness', 'something else', 'contentment', 'amusement'}, 'arshile-gorky_bound-in-sleep': {'sadness', 'contentment', 'awe', 'amusement'}, 'corneliu-michailescu_composition-with-romanian-motifs': {'excitement', 'amusement'}, 'diego-rivera_woman-at-a-well-1913': {'something else', 'fear', 'excitement', 'awe', 'amusement'}, 'eileen-agar_the-shell-1934': {'something else', 'awe', 'amusement'}, 'fernand-leger_red-pot-1926': {'excitement', 'something else', 'disgust', 'amusement'}, 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921': {'something else', 'fear', 'excitement', 'disgust', 'sadness', 'contentment', 'awe', 'amusement'}, 'fernand-leger_the-study-for-the-city-centre-1927': {'sadness', 'contentment', 'amusement'}, 'gosta-adrian-nilsson_fantasi-1917': {'something else', 'fear'}, 'henri-laurens_le-grand-adieu-1941': {'sadness', 'something else', 'disgust'}, 'jacques-villon_4e-bucolique-pollion-from-les-bucoliques': {'sadness', 'awe', 'fear'}, 'jacques-villon_birds-in-flight-1958': {'contentment', 'awe', 'something else'}, 'kazimir-malevich_the-athlete-of-the-future-1913': {'contentment', 'fear', 'something else', 'amusement'}, 'louis-marcoussis_the-cardplayer-1921': {'contentment', 'fear', 'disgust', 'amusement'}, 'lyonel-feininger_gaberndorf-ii-1924': {'something else', 'contentment', 'fear'}, 'marc-chagall_marketplace-in-vitebsk-1917': {'contentment', 'disgust', 'amusement'}, 'marc-chagall_the-holy-coachman-1912': {'awe', 'amusement'}, 'mario-sironi_the-ballerina': {'sadness', 'something else', 'awe'}, 'miriam-schapiro_pas-de-deux-1986': {'excitement', 'amusement'}, 'olexandr-archipenko_king-solomon': {'something else', 'disgust', 'fear', 'amusement'}, 'olexandr-archipenko_madonna-of-the-rocks-1912': {'contentment', 'awe', 'something else', 'amusement'}, 'olexandr-archipenko_two-nude-female-figures-with-a-cloth': {'something else', 'disgust', 'contentment', 'awe', 'amusement'}, 'pablo-picasso_a-dream-1932': {'sadness', 'contentment', 'disgust', 'amusement'}, 'pyotr-konchalovsky_still-life-1911': {'something else', 'disgust', 'sadness', 'contentment', 'awe'}, 'roy-lichtenstein_woman-with-hat': {'something else', 'disgust', 'amusement'}, 'salvador-dali_crystalline-still-life': {'disgust', 'contentment', 'awe', 'amusement', 'anger'}, 'alvaro-lapa_o-casamento-1967': {'something else', 'fear', 'amusement'}, 'brice-marden_avrutun-1971': {'sadness', 'something else', 'contentment'}, 'brice-marden_for-caroline-1977': {'something else', 'fear'}, 'denise-green_untitled-vessel-10-1977': {'sadness', 'contentment', 'fear'}, 'eva-hesse_addendum-1967': {'something else', 'amusement'}, 'eva-hesse_untitled-1966': {'something else', 'awe', 'fear'}, 'henk-peeters_untitled-3': {'something else', 'fear', 'disgust', 'amusement'}, 'john-mclaughlin_untitled-composition-1953': {'excitement', 'something else', 'anger', 'disgust'}, 'leo-villareal_big-bang-2008': {'excitement', 'something else', 'awe', 'amusement'}, 'mira-schendel_untitled-from-cadernos-series-1971': {'excitement', 'contentment', 'something else', 'sadness'}, 'myron-stout_untitled-5-2-17-55-1955': {'something else', 'excitement', 'disgust', 'sadness', 'amusement'}, 'pino-pinelli_pittura-b-g-1991': {'something else', 'disgust', 'contentment', 'amusement'}, 'pino-pinelli_pittura-bl-g-1993': {'excitement', 'something else', 'awe', 'amusement'}, 'richard-tuttle_sand-tree-2-1988': {'something else', 'disgust', 'sadness', 'contentment', 'anger'}, 'robert-ryman_untitled-1959': {'something else', 'excitement', 'disgust', 'sadness', 'contentment', 'awe', 'amusement', 'anger'}, 'ronald-davis_zig-zag-times-two-1966': {'excitement', 'something else', 'awe', 'contentment'}, 'ruth-vollmer_sunflower-head-series-1973-1': {'something else', 'fear', 'awe', 'amusement'}, 'tony-smith_untitled-1956': {'contentment', 'disgust', 'fear'}, 'yves-klein_untitled-blue-monochrome-1959-2': {'sadness', 'something else', 'contentment'}})
99

In [ ]:
# Read in file
#results_df = pd.read_csv("/content/drive/Shareddrives/LLMs_Art_Project/Data/Results/Qwen/()_results_0shot.csv")

# Iterate over rows
for index, row in results_df.iterrows():
    painting = row["test_painting"]

    # Get possible correct emotions
    emotions = emotions_map[painting]

    # Safely convert predicted_emotion to string and then to lowercase
    predicted_emotion = str(row["predicted_emotion"]).lower()

    # added just now
    if predicted_emotion =="something-else": predicted_emotion = "something else"

    # Calculate accuracy
    if predicted_emotion in emotions:
        results_df.at[index, "accuracy"] = 1
    else:
        results_df.at[index, "accuracy"] = 0

    # print(f"Prediction: {predicted_emotion}. |{results_df.iloc[index]["accuracy"]}|  Emotions: {emotions}")

# Calculate Overall Accuracy
overall_accuracy = results_df["accuracy"].mean()
print(f"Overall Accuracy: {overall_accuracy*100:.2f}%")

Overall Accuracy: 59.00%

In [ ]:
results_df.head()

,test_painting,demo_paintings,demo_utterances,predicted_emotion,generated_description,embeddings,embedding_vec,max_cosine_similarity,best_gt_index,best_gt_description,accuracy
0,hans-hofmann_nulli-secundus-1964,[],[],Something-Else,I feel like this painting is very abstract and...,"[-0.0195406936109066, -0.05804502218961716, 0....","[-0.0195406936109066, -0.05804502218961716, 0....",0.698429,101,The painting makes me feel like I am walking d...,0.0
1,gene-davis_color-needles-1984,[],[],Awe,The use of thin lines in a horizontal pattern ...,"[0.016316348686814308, 0.014112216420471668, 0...","[0.016316348686814308, 0.014112216420471668, 0...",0.663300,423,The center of the painting seems to be bright....,0.0
2,arshile-gorky_bound-in-sleep,[],[],Awe,The use of bright colors and the way the face ...,"[-0.014129390008747578, -0.02588188275694847, ...","[-0.014129390008747578, -0.02588188275694847, ...",0.758641,541,"the calm demeanor of the face, the chalk like ...",1.0
3,pino-pinelli_pittura-b-g-1991,[],[],amusement,it looks like a donut with the white cream and...,"[-0.0293964222073555, 0.035130731761455536, -0...","[-0.0293964222073555, 0.035130731761455536, -0...",0.626463,766,The fruity donuts glued onto the wall is funny...,1.0
4,pyotr-konchalovsky_still-life-1911,[],[],Contentment,The shapes are simple and make me feel calm,"[-0.0008190866210497916, 0.009310310706496239,...","[-0.0008190866210497916, 0.009310310706496239,...",0.665668,694,i dont feel anything when I look at this,1.0

### Output new results_df to file

In [ ]:
# Outut new results_df to file
output_path = "/content/drive/Shareddrives/LLMs_Art_Project/Data/Results/Final_Results/human_results_embeddedandmetrics.csv"
human_results_df.to_csv(output_path, index=False)
print("Saved results to:", output_path)

Saved results to: /content/drive/Shareddrives/LLMs_Art_Project/Data/Results/Final_Results/human_results_embeddedandmetrics.csv

## extra

In [ ]:
paintings_map = defaultdict(set)
for index, row in all_test_set_df.iterrows():
    painting = row['painting']
    emotion = row['emotion'].lower()
    paintings_map[emotion].add(painting)

print(paintings_map)

paintings_map_results = defaultdict(set)
for index, row in results_df.iterrows():
    painting = row['test_painting']
    emotion = row['predicted_emotion'].lower()
    if emotion =="something-else": emotion = "something else"
    paintings_map_results[emotion].add(painting)

print(paintings_map_results)

for emotion in paintings_map:
  print(emotion)
  print(len(paintings_map[emotion]))
  print(len(paintings_map_results[emotion]))

defaultdict(<class 'set'>, {'sadness': {'barnett-newman_onement-v-1952', 'aaron-siskind_chicago-1951', 'andre-pierre-arnal_pliage-folded-painting-1975', 'anne-appleby_appleby-2011', 'brice-marden_etchings-to-rexroth-1-1986', 'pablo-picasso_a-dream-1932', 'jack-tworkov_indian-red-series-i-1979', 'richard-tuttle_sand-tree-2-1988', 'henri-laurens_le-grand-adieu-1941', 'robert-ryman_untitled-1959', 'jackson-pollock_black-white-number-20-1951', 'hans-hofmann_little-cherry-1965', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'myron-stout_untitled-5-2-17-55-1955', 'gene-davis_cannonball-1969', 'fernand-leger_the-study-for-the-city-centre-1927', 'paul-jenkins_phenomena-lands-end', 'albert-gleizes_untitled-2', 'pyotr-konchalovsky_still-life-1911', 'joan-snyder_perpetuo-eternally-2004', 'charles-hinman_dance-1972', 'mira-schendel_untitled-from-cadernos-series-1971', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'ian-davenport_puddle-painting-magenta-2008', 'mario-sironi_the-ballerina', 'brice-marden_avrutun-1971', 'arshile-gorky_bound-in-sleep', 'yves-klein_untitled-blue-monochrome-1959-2', 'jacques-villon_4e-bucolique-pollion-from-les-bucoliques', 'hans-hofmann_gloriamundi-1963', 'denise-green_untitled-vessel-10-1977', 'franz-kline_buttress-1956', 'helen-frankenthaler_tuscany-1963', 'anne-truitt_knight-s-heritage-1963'}, 'fear': {'aaron-siskind_chicago-1951', 'andre-pierre-arnal_pliage-folded-painting-1975', 'tony-smith_untitled-1956', 'angelo-de-sousa_sem-titulo-1988', 'ralph-hotere_song-cycle-1975', 'lyonel-feininger_gaberndorf-ii-1924', 'jackson-pollock_black-white-number-20-1951', 'ruth-vollmer_sunflower-head-series-1973-1', 'salvador-dali_abraham-pater-multarem-gentium-genesis-12-1f-1967', 'esteban-vicente_balada-1959', 'hans-hofmann_little-cherry-1965', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'louis-marcoussis_the-cardplayer-1921', 'michel-carrade_unknown-title-14', 'hans-hofmann_nulli-secundus-1964', 'ronnie-landfield_circe-s-palace-1982', 'brice-marden_for-caroline-1977', 'olexandr-archipenko_king-solomon', 'diego-rivera_woman-at-a-well-1913', 'kazimir-malevich_the-athlete-of-the-future-1913', 'helen-frankenthaler_tuscany-1963', 'joan-snyder_perpetuo-eternally-2004', 'eva-hesse_untitled-1966', 'william-baziotes_cyclops-1947', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'gosta-adrian-nilsson_fantasi-1917', 'alvaro-lapa_o-casamento-1967', 'henk-peeters_untitled-3', 'jacques-villon_4e-bucolique-pollion-from-les-bucoliques', 'hans-hofmann_bird-cage-variation-ii-1958', 'friedel-dzubas_echo-1958', 'denise-green_untitled-vessel-10-1977', 'franz-kline_buttress-1956', 'theodoros-stamos_untitled-columns-of-fire-1956', 'anne-truitt_knight-s-heritage-1963', 'richard-tuttle_20-pearls-1-2003'}, 'something else': {'anne-appleby_appleby-2011', 'aki-kuroda_untitled-1998', 'ruth-vollmer_sunflower-head-series-1973-1', 'michel-carrade_unknown-title-14', 'myron-stout_untitled-5-2-17-55-1955', 'william-baziotes_cyclops-1947', 'walter-darby-bannard_green-valentine-3-1965', 'alvaro-lapa_o-casamento-1967', 'henk-peeters_untitled-3', 'hans-hofmann_bird-cage-variation-ii-1958', 'jacques-villon_birds-in-flight-1958', 'hans-hofmann_gloriamundi-1963', 'gene-davis_color-needles-1984', 'leo-villareal_big-bang-2008', 'theodoros-stamos_untitled-columns-of-fire-1956', 'anne-truitt_knight-s-heritage-1963', 'sam-gilliam_buoy-landscape-ii-1982', 'atsuko-tanaka_untitled-1963', 'leon-berkowitz_dark-light-rose-gold-1978', 'lyonel-feininger_gaberndorf-ii-1924', 'philip-guston_to-b-w-t', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'pino-pinelli_pittura-bl-g-1993', 'pyotr-konchalovsky_still-life-1911', 'william-scott_blue-form-on-white-1964', 'alfred-jensen_interlacing-colors-i-1959', 'miriam-schapiro_fanfare-1968', 'brice-marden_avrutun-1971', 'yves-klein_untitled-blue-monochrome-1959-2', 'helen-frankenthaler_blue-form-in-a-scene-1961', 'friedel-dzubas_echo-1958', 'olexandr-archipenko_two-nude-female-figures-with-a-cloth', 'eva-hesse_addendum-1967', 'hans-hofmann_little-cherry-1965', 'barnett-newman_onement-v-1952', 'aaron-siskind_chicago-1951', 'barnett-newman_the-wild-1950', 'olivier-debre_rouge-coule-de-touraine-1990', 'kenzo-okada_untitled', 'brice-marden_etchings-to-rexroth-1-1986', 'olexandr-archipenko_madonna-of-the-rocks-1912', 'dan-christensen_untitled-1968', 'richard-tuttle_sand-tree-2-1988', 'henri-laurens_le-grand-adieu-1941', 'ralph-hotere_song-cycle-1975', 'wu-guanzhong_white-poplar-woods', 'robert-ryman_untitled-1959', 'friedel-dzubas_tundra-ii-1962', 'helen-frankenthaler_distillation-1973', 'brice-marden_for-caroline-1977', 'olexandr-archipenko_king-solomon', 'albert-gleizes_untitled-2', 'eva-hesse_untitled-1966', 'mira-schendel_untitled-from-cadernos-series-1971', 'gosta-adrian-nilsson_fantasi-1917', 'clyfford-still_ph-118-1947', 'mario-sironi_the-ballerina', 'richard-tuttle_20-pearls-1-2003', 'andre-pierre-arnal_pliage-folded-painting-1975', 'fernand-leger_red-pot-1926', 'john-mclaughlin_untitled-composition-1953', 'howard-mehring_all-green-1958', 'pino-pinelli_pittura-b-g-1991', 'angelo-de-sousa_sem-titulo-1988', 'salvador-dali_abraham-pater-multarem-gentium-genesis-12-1f-1967', 'gene-davis_diamond-jim-1972', 'gene-davis_cannonball-1969', 'paul-jenkins_phenomena-lands-end', 'diego-rivera_woman-at-a-well-1913', 'eileen-agar_the-shell-1934', 'kazimir-malevich_the-athlete-of-the-future-1913', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'roy-lichtenstein_woman-with-hat', 'ronald-davis_zig-zag-times-two-1966', 'jackson-pollock_number-12-1949', 'barnett-newman_tenth-station-1965', 'helen-frankenthaler_tuscany-1963'}, 'contentment': {'barnett-newman_the-wild-1950', 'aaron-siskind_chicago-1951', 'andre-pierre-arnal_pliage-folded-painting-1975', 'kenzo-okada_untitled', 'anne-appleby_appleby-2011', 'sam-gilliam_buoy-landscape-ii-1982', 'brice-marden_etchings-to-rexroth-1-1986', 'pablo-picasso_a-dream-1932', 'howard-mehring_all-green-1958', 'olexandr-archipenko_madonna-of-the-rocks-1912', 'aki-kuroda_untitled-1998', 'jack-tworkov_indian-red-series-i-1979', 'dan-christensen_untitled-1968', 'pino-pinelli_pittura-b-g-1991', 'richard-tuttle_sand-tree-2-1988', 'ralph-hotere_song-cycle-1975', 'leon-berkowitz_dark-light-rose-gold-1978', 'wu-guanzhong_white-poplar-woods', 'marc-chagall_marketplace-in-vitebsk-1917', 'robert-ryman_untitled-1959', 'lyonel-feininger_gaberndorf-ii-1924', 'salvador-dali_abraham-pater-multarem-gentium-genesis-12-1f-1967', 'philip-guston_to-b-w-t', 'gene-davis_diamond-jim-1972', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'louis-marcoussis_the-cardplayer-1921', 'michel-carrade_unknown-title-14', 'hans-hofmann_nulli-secundus-1964', 'ronnie-landfield_circe-s-palace-1982', 'gene-davis_cannonball-1969', 'salvador-dali_crystalline-still-life', 'fernand-leger_the-study-for-the-city-centre-1927', 'paul-jenkins_phenomena-lands-end', 'kazimir-malevich_the-athlete-of-the-future-1913', 'albert-gleizes_untitled-2', 'pyotr-konchalovsky_still-life-1911', 'helen-frankenthaler_tuscany-1963', 'joan-snyder_perpetuo-eternally-2004', 'william-scott_blue-form-on-white-1964', 'charles-hinman_dance-1972', 'mira-schendel_untitled-from-cadernos-series-1971', 'tony-smith_untitled-1956', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'walter-darby-bannard_green-valentine-3-1965', 'alfred-jensen_interlacing-colors-i-1959', 'miriam-schapiro_fanfare-1968', 'brice-marden_avrutun-1971', 'ronald-davis_zig-zag-times-two-1966', 'arshile-gorky_bound-in-sleep', 'yves-klein_untitled-blue-monochrome-1959-2', 'gerhard-richter_mediation', 'hans-hofmann_bird-cage-variation-ii-1958', 'jacques-villon_birds-in-flight-1958', 'denise-green_untitled-vessel-10-1977', 'olexandr-archipenko_two-nude-female-figures-with-a-cloth', 'gene-davis_color-needles-1984', 'barnett-newman_tenth-station-1965', 'theodoros-stamos_untitled-columns-of-fire-1956', 'anne-truitt_knight-s-heritage-1963', 'richard-tuttle_20-pearls-1-2003'}, 'awe': {'aaron-siskind_chicago-1951', 'olivier-debre_rouge-coule-de-touraine-1990', 'andre-pierre-arnal_pliage-folded-painting-1975', 'kenzo-okada_untitled', 'sam-gilliam_buoy-landscape-ii-1982', 'brice-marden_etchings-to-rexroth-1-1986', 'olexandr-archipenko_madonna-of-the-rocks-1912', 'aki-kuroda_untitled-1998', 'dan-christensen_untitled-1968', 'wu-guanzhong_white-poplar-woods', 'robert-ryman_untitled-1959', 'ruth-vollmer_sunflower-head-series-1973-1', 'salvador-dali_abraham-pater-multarem-gentium-genesis-12-1f-1967', 'hans-hofmann_little-cherry-1965', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'pino-pinelli_pittura-bl-g-1993', 'michel-carrade_unknown-title-14', 'salvador-dali_crystalline-still-life', 'paul-jenkins_phenomena-lands-end', 'diego-rivera_woman-at-a-well-1913', 'eileen-agar_the-shell-1934', 'pyotr-konchalovsky_still-life-1911', 'charles-hinman_dance-1972', 'eva-hesse_untitled-1966', 'walter-darby-bannard_green-valentine-3-1965', 'clyfford-still_ph-118-1947', 'mario-sironi_the-ballerina', 'miriam-schapiro_fanfare-1968', 'ronald-davis_zig-zag-times-two-1966', 'arshile-gorky_bound-in-sleep', 'jackson-pollock_number-12-1949', 'hans-hofmann_bird-cage-variation-ii-1958', 'jacques-villon_birds-in-flight-1958', 'marc-chagall_the-holy-coachman-1912', 'olexandr-archipenko_two-nude-female-figures-with-a-cloth', 'leo-villareal_big-bang-2008', 'jacques-villon_4e-bucolique-pollion-from-les-bucoliques', 'anne-truitt_knight-s-heritage-1963', 'richard-tuttle_20-pearls-1-2003'}, 'excitement': {'barnett-newman_the-wild-1950', 'olivier-debre_rouge-coule-de-touraine-1990', 'andre-pierre-arnal_pliage-folded-painting-1975', 'fernand-leger_red-pot-1926', 'john-mclaughlin_untitled-composition-1953', 'sam-gilliam_buoy-landscape-ii-1982', 'brice-marden_etchings-to-rexroth-1-1986', 'aki-kuroda_untitled-1998', 'jack-tworkov_indian-red-series-i-1979', 'angelo-de-sousa_sem-titulo-1988', 'dan-christensen_untitled-1968', 'ralph-hotere_song-cycle-1975', 'atsuko-tanaka_untitled-1963', 'leon-berkowitz_dark-light-rose-gold-1978', 'robert-ryman_untitled-1959', 'salvador-dali_abraham-pater-multarem-gentium-genesis-12-1f-1967', 'friedel-dzubas_tundra-ii-1962', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'pino-pinelli_pittura-bl-g-1993', 'michel-carrade_unknown-title-14', 'myron-stout_untitled-5-2-17-55-1955', 'hans-hofmann_nulli-secundus-1964', 'miriam-schapiro_pas-de-deux-1986', 'diego-rivera_woman-at-a-well-1913', 'mira-schendel_untitled-from-cadernos-series-1971', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'walter-darby-bannard_green-valentine-3-1965', 'clyfford-still_ph-118-1947', 'ian-davenport_puddle-painting-magenta-2008', 'miriam-schapiro_fanfare-1968', 'corneliu-michailescu_composition-with-romanian-motifs', 'ronald-davis_zig-zag-times-two-1966', 'jackson-pollock_number-12-1949', 'gerhard-richter_mediation', 'hans-hofmann_bird-cage-variation-ii-1958', 'hans-hofmann_gloriamundi-1963', 'barnett-newman_tenth-station-1965', 'leo-villareal_big-bang-2008', 'ronnie-landfield_circe-s-palace-1982', 'anne-truitt_knight-s-heritage-1963', 'richard-tuttle_20-pearls-1-2003'}, 'amusement': {'andre-pierre-arnal_pliage-folded-painting-1975', 'anne-appleby_appleby-2011', 'fernand-leger_red-pot-1926', 'sam-gilliam_buoy-landscape-ii-1982', 'pablo-picasso_a-dream-1932', 'olexandr-archipenko_madonna-of-the-rocks-1912', 'jack-tworkov_indian-red-series-i-1979', 'dan-christensen_untitled-1968', 'pino-pinelli_pittura-b-g-1991', 'ralph-hotere_song-cycle-1975', 'atsuko-tanaka_untitled-1963', 'wu-guanzhong_white-poplar-woods', 'leon-berkowitz_dark-light-rose-gold-1978', 'marc-chagall_marketplace-in-vitebsk-1917', 'robert-ryman_untitled-1959', 'jackson-pollock_black-white-number-20-1951', 'ruth-vollmer_sunflower-head-series-1973-1', 'esteban-vicente_balada-1959', 'friedel-dzubas_tundra-ii-1962', 'gene-davis_diamond-jim-1972', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'louis-marcoussis_the-cardplayer-1921', 'helen-frankenthaler_distillation-1973', 'pino-pinelli_pittura-bl-g-1993', 'myron-stout_untitled-5-2-17-55-1955', 'salvador-dali_crystalline-still-life', 'fernand-leger_the-study-for-the-city-centre-1927', 'miriam-schapiro_pas-de-deux-1986', 'olexandr-archipenko_king-solomon', 'diego-rivera_woman-at-a-well-1913', 'albert-gleizes_untitled-2', 'eileen-agar_the-shell-1934', 'kazimir-malevich_the-athlete-of-the-future-1913', 'william-scott_blue-form-on-white-1964', 'charles-hinman_dance-1972', 'william-baziotes_cyclops-1947', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'clyfford-still_ph-118-1947', 'alvaro-lapa_o-casamento-1967', 'ian-davenport_puddle-painting-magenta-2008', 'roy-lichtenstein_woman-with-hat', 'eva-hesse_addendum-1967', 'corneliu-michailescu_composition-with-romanian-motifs', 'arshile-gorky_bound-in-sleep', 'henk-peeters_untitled-3', 'gerhard-richter_mediation', 'helen-frankenthaler_blue-form-in-a-scene-1961', 'hans-hofmann_bird-cage-variation-ii-1958', 'marc-chagall_the-holy-coachman-1912', 'hans-hofmann_gloriamundi-1963', 'olexandr-archipenko_two-nude-female-figures-with-a-cloth', 'gene-davis_color-needles-1984', 'barnett-newman_tenth-station-1965', 'leo-villareal_big-bang-2008', 'anne-truitt_knight-s-heritage-1963', 'richard-tuttle_20-pearls-1-2003'}, 'disgust': {'fernand-leger_red-pot-1926', 'john-mclaughlin_untitled-composition-1953', 'sam-gilliam_buoy-landscape-ii-1982', 'brice-marden_etchings-to-rexroth-1-1986', 'pablo-picasso_a-dream-1932', 'howard-mehring_all-green-1958', 'tony-smith_untitled-1956', 'pino-pinelli_pittura-b-g-1991', 'richard-tuttle_sand-tree-2-1988', 'henri-laurens_le-grand-adieu-1941', 'atsuko-tanaka_untitled-1963', 'marc-chagall_marketplace-in-vitebsk-1917', 'robert-ryman_untitled-1959', 'philip-guston_to-b-w-t', 'friedel-dzubas_tundra-ii-1962', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'louis-marcoussis_the-cardplayer-1921', 'myron-stout_untitled-5-2-17-55-1955', 'salvador-dali_crystalline-still-life', 'olexandr-archipenko_king-solomon', 'pyotr-konchalovsky_still-life-1911', 'joan-snyder_perpetuo-eternally-2004', 'william-scott_blue-form-on-white-1964', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'roy-lichtenstein_woman-with-hat', 'jackson-pollock_number-12-1949', 'henk-peeters_untitled-3', 'helen-frankenthaler_blue-form-in-a-scene-1961', 'hans-hofmann_bird-cage-variation-ii-1958', 'olexandr-archipenko_two-nude-female-figures-with-a-cloth', 'franz-kline_buttress-1956', 'ronnie-landfield_circe-s-palace-1982', 'anne-truitt_knight-s-heritage-1963', 'richard-tuttle_20-pearls-1-2003'}, 'anger': {'barnett-newman_onement-v-1952', 'andre-pierre-arnal_pliage-folded-painting-1975', 'kenzo-okada_untitled', 'anne-appleby_appleby-2011', 'john-mclaughlin_untitled-composition-1953', 'brice-marden_etchings-to-rexroth-1-1986', 'jack-tworkov_indian-red-series-i-1979', 'angelo-de-sousa_sem-titulo-1988', 'richard-tuttle_sand-tree-2-1988', 'ralph-hotere_song-cycle-1975', 'robert-ryman_untitled-1959', 'jackson-pollock_black-white-number-20-1951', 'philip-guston_to-b-w-t', 'gene-davis_diamond-jim-1972', 'helen-frankenthaler_distillation-1973', 'hans-hofmann_nulli-secundus-1964', 'salvador-dali_crystalline-still-life', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'ian-davenport_puddle-painting-magenta-2008', 'jackson-pollock_number-12-1949', 'gerhard-richter_mediation', 'hans-hofmann_bird-cage-variation-ii-1958', 'friedel-dzubas_echo-1958', 'franz-kline_buttress-1956', 'theodoros-stamos_untitled-columns-of-fire-1956'}})
defaultdict(<class 'set'>, {'something else': {'barnett-newman_onement-v-1952', 'ruth-vollmer_sunflower-head-series-1973-1', 'andre-pierre-arnal_pliage-folded-painting-1975', 'kenzo-okada_untitled', 'brice-marden_etchings-to-rexroth-1-1986', 'esteban-vicente_balada-1959', 'hans-hofmann_bird-cage-variation-ii-1958', 'jacques-villon_birds-in-flight-1958', 'barnett-newman_tenth-station-1965', 'michel-carrade_unknown-title-14', 'howard-mehring_all-green-1958', 'aki-kuroda_untitled-1998', 'hans-hofmann_nulli-secundus-1964', 'walter-darby-bannard_green-valentine-3-1965', 'angelo-de-sousa_sem-titulo-1988', 'alfred-jensen_interlacing-colors-i-1959', 'marc-chagall_marketplace-in-vitebsk-1917', 'alvaro-lapa_o-casamento-1967'}, 'awe': {'john-mclaughlin_untitled-composition-1953', 'olexandr-archipenko_madonna-of-the-rocks-1912', 'tony-smith_untitled-1956', 'jack-tworkov_indian-red-series-i-1979', 'ralph-hotere_song-cycle-1975', 'leon-berkowitz_dark-light-rose-gold-1978', 'wu-guanzhong_white-poplar-woods', 'lyonel-feininger_gaberndorf-ii-1924', 'philip-guston_to-b-w-t', 'fernand-leger_skating-rink-drawing-of-the-curtain-of-scene-1921', 'louis-marcoussis_the-cardplayer-1921', 'pino-pinelli_pittura-bl-g-1993', 'myron-stout_untitled-5-2-17-55-1955', 'anne-truitt_knight-s-heritage-1963', 'salvador-dali_crystalline-still-life', 'paul-jenkins_phenomena-lands-end', 'kazimir-malevich_the-athlete-of-the-future-1913', 'joan-snyder_perpetuo-eternally-2004', 'william-scott_blue-form-on-white-1964', 'eva-hesse_untitled-1966', 'mira-schendel_untitled-from-cadernos-series-1971', 'gosta-adrian-nilsson_fantasi-1917', 'william-baziotes_cyclops-1947', 'brice-marden_avrutun-1971', 'eva-hesse_addendum-1967', 'ronald-davis_zig-zag-times-two-1966', 'arshile-gorky_bound-in-sleep', 'helen-frankenthaler_blue-form-in-a-scene-1961', 'gerhard-richter_mediation', 'marc-chagall_the-holy-coachman-1912', 'denise-green_untitled-vessel-10-1977', 'olexandr-archipenko_two-nude-female-figures-with-a-cloth', 'gene-davis_color-needles-1984', 'leo-villareal_big-bang-2008', 'helen-frankenthaler_tuscany-1963', 'hans-hofmann_little-cherry-1965', 'richard-tuttle_20-pearls-1-2003'}, 'amusement': {'corneliu-michailescu_composition-with-romanian-motifs', 'albert-gleizes_untitled-2', 'pino-pinelli_pittura-b-g-1991', 'ronnie-landfield_circe-s-palace-1982', 'miriam-schapiro_fanfare-1968'}, 'contentment': {'olexandr-archipenko_king-solomon', 'robert-ryman_untitled-1959', 'diego-rivera_woman-at-a-well-1913', 'pyotr-konchalovsky_still-life-1911', 'anne-appleby_appleby-2011', 'fernand-leger_red-pot-1926', 'sam-gilliam_buoy-landscape-ii-1982', 'pablo-picasso_a-dream-1932', 'friedel-dzubas_tundra-ii-1962', 'gene-davis_diamond-jim-1972', 'charles-hinman_dance-1972', 'helen-frankenthaler_distillation-1973', 'hans-hofmann_gloriamundi-1963', 'gene-davis_untitled-pink-stripes-gray-box-1976', 'brice-marden_for-caroline-1977', 'gene-davis_cannonball-1969', 'fernand-leger_the-study-for-the-city-centre-1927'}, 'fear': {'aaron-siskind_chicago-1951', 'jackson-pollock_black-white-number-20-1951', 'henk-peeters_untitled-3', 'yves-klein_untitled-blue-monochrome-1959-2', 'franz-kline_buttress-1956', 'theodoros-stamos_untitled-columns-of-fire-1956'}, 'anger': {'barnett-newman_the-wild-1950', 'richard-tuttle_sand-tree-2-1988', 'jackson-pollock_number-12-1949'}, 'excitement': {'olivier-debre_rouge-coule-de-touraine-1990', 'atsuko-tanaka_untitled-1963', 'friedel-dzubas_echo-1958', 'dan-christensen_untitled-1968', 'roy-lichtenstein_woman-with-hat', 'clyfford-still_ph-118-1947', 'ian-davenport_puddle-painting-magenta-2008', 'mario-sironi_the-ballerina', 'miriam-schapiro_pas-de-deux-1986'}, 'sadness': {'salvador-dali_abraham-pater-multarem-gentium-genesis-12-1f-1967', 'jacques-villon_4e-bucolique-pollion-from-les-bucoliques', 'henri-laurens_le-grand-adieu-1941'}, 'emotion': {'eileen-agar_the-shell-1934'}})
sadness
34
3
fear
36
6
something else
77
18
contentment
60
17
awe
39
37
excitement
41
9
amusement
56
5
disgust
34
0
anger
25
3